### ISSUE TITLE
Clients receive only part of large datas from the server.

### ISSUE THREAD

**Issue by FlafyDev** [noobswestand/Python-Server-GM-Client#3]
Hi again, I have another problem.
For some reason, whenever I send from the server a socket with a large buffer(like a 12000~ characters string) to all the clients, on clients that are connected from a different network of the server don't get all the data, just part of it... Clients that are connected to the server from the same network of the server, get all the data.

I made a post about it in StackOverflow: https://stackoverflow.com/q/60744574/10849036
But no buddy answered. Maybe you know what to do? Thanks.

**Comment by noobswestand** [comment]
Hello,
It's interesting that it works on LAN.Can you try to send a large packet to the server and see if the server gets it all?
It might be a bug with the client.  I will have to test and see tonight.  If the packet is broken up (in the case of very large packets), then the client should be able to assemble it again.The server should also do this.

    On Thursday, March 19, 2020, 10:16:39 AM CDT, FlafyMation <notifications@github.com> wrote:  
 
 


Hi again, I have another problem.
For some reason, whenever I send from the server a socket with a large buffer(like a 12000~ characters string) to all the clients, on clients that are connected from a different network of the server don't get all the data, just part of it... Clients that are connected to the server from the same network of the server, get all the data.

I made a post about it in StackOverflow: https://stackoverflow.com/q/60744574/10849036
But no buddy answered. Maybe you know what to do? Thanks.

**Comment by FlafyDev** [comment]
> Hello, It's interesting that it works on LAN.Can you try to send a large packet to the server and see if the server gets it all? It might be a bug with the client.  I will have to test and see tonight.  If the packet is broken up (in the case of very large packets), then the client should be able to assemble it again.The server should also do this. On Thursday, March 19, 2020, 10:16:39 AM CDT, FlafyMation <notifications@github.com> wrote: Hi again, I have another problem. For some reason, whenever I send from the server a socket with a large buffer(like a 12000~ characters string) to all the clients, on clients that are connected from a different network of the server don't get all the data, just part of it... Clients that are connected to the server from the same network of the server, get all the data. I made a post about it in StackOverflow: https://stackoverflow.com/q/60744574/10849036 But no buddy answered. Maybe you know what to do? Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I'm already doing it. The server gets all the data from every client even if it's large. Let me know when you find the problem :)

**Comment by noobswestand** [comment]
Hello,
I fixed the problem for the client. It should be on github.  Let me know if this works
    On Thursday, March 19, 2020, 01:37:05 PM CDT, FlafyMation <notifications@github.com> wrote:  
 
 



Hello, It's interesting that it works on LAN.Can you try to send a large packet to the server and see if the server gets it all? It might be a bug with the client.  I will have to test and see tonight.  If the packet is broken up (in the case of very large packets), then the client should be able to assemble it again.The server should also do this. On Thursday, March 19, 2020, 10:16:39 AM CDT, FlafyMation notifications@github.com wrote: Hi again, I have another problem. For some reason, whenever I send from the server a socket with a large buffer(like a 12000~ characters string) to all the clients, on clients that are connected from a different network of the server don't get all the data, just part of it... Clients that are connected to the server from the same network of the server, get all the data. I made a post about it in StackOverflow: https://stackoverflow.com/q/60744574/10849036 But no buddy answered. Maybe you know what to do? Thanks. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


I'm already doing it. The server gets all the data from every client even if it's large. Let me know when you find the problem :)

**Comment by FlafyDev** [comment]
> Hello, I fixed the problem for the client. It should be on github.  Let me know if this works

Hi, I redownloaded the files and made the server send to the client a long string once again. But it didn't get anything this time...

Clients on the same network of the server get the long string just fine, but clients on a different network from the server, don't get any string at all(The function that the HandlePacketClient should run doesn't run), and also cannot receive sockets after sending them the long string(But can send sockets)...

Am I doing something wrong? Is it working fine for you?

Thank you.

**Comment by FlafyDev** [comment]
Hi, any updates?

**Comment by noobswestand** [comment]
Hello,I got your last message. I was just a little busy yesterday. Let me test more to find out.
In the mean time, I'm pretty sure you can break up the large packet into a bunch of smaller ones and it will work just fine.  You don't have to space them out or anything.  You can just call sendmessage a bunch of times in a row.
    On Saturday, March 21, 2020, 08:04:04 AM CDT, FlafyMation <notifications@github.com> wrote:  
 
 


Hi, any updates?

**Comment by noobswestand** [comment]
Hello,
I think I fixed it. I tested it, and it seems to be working now. The client was not properly putting the packets together when they would be split up because of the sizeHowever, the maximum packet size is 65535 bytes. This is due to the header using 2 bytes to write the packet size (ushort). This can be changed, but I feel like anything more than 65KB per packet is maybe a little much.
If you need to change this:Change global.Buffer_header in obj_client createChange self.BufferHeader in Network.py __init__
    On Saturday, March 21, 2020, 08:04:04 AM CDT, FlafyMation <notifications@github.com> wrote:  
 
 


Hi, any updates?

**Comment by FlafyDev** [comment]
It works perfectly now. Thank you, you're amazing!
